### ISSUE TITLE
how to install?

### ISSUE THREAD

**Issue by mortezakarimi** [esc/conda-zsh-completion#12] opened 2019-02-19 09:07 UTC
Please add installation instruction

I read `_conda` file but don't understand!

**Comment by esc** [comment] 2019-03-09 04:14
Here is the relevant snippet:

```
# To use this completion drop it somewhere in you '$fpath', e.g.:
#
#     $ git clone $CLONEURL
#     $ fpath+=$PWD/conda-zsh-completion
#     $ compinit conda
```

I do realize, that documentation is a bit lacking right now, you can also look at:

#7 and #4 for more info

**Comment by esc** [comment] 2019-03-09 04:15
I will close this for now, as we are in the progress of getting better docs, please feel free to re-open, if you are still having issues. In this case also list:

* What did you do?
* What did you expect?
* What happend instead?

**Closed by esc** 2019-03-09 04:15 UTC

**Comment by joleroi** [comment] 2019-09-04 11:07
* What did you do?

Follow the install instructions in `_conda`, .i.e. add `fpath+=/<...>/conda-zsh-completion` to `~/.zshrc` before initializing `oh-my-zsh`

* What did you expect?
That conda autocompletion works

* What happend instead?

It didn't 😢  Then I strumbled across this issue which solved my problem. Apparently, I have to run `compinit conda` and not just `compinit` (as suggested in the `_conda` file). Maybe this is obvious to someone who is familiar with `zsh` but I just go started so this was a (easily resolvable) hurdle for me

**Comment by haugstve** [comment] 2019-10-28 16:00
I ended up in the same situation. With Mac OS switching from `bash` to `zsh` I'm guessing there will be more users like me. 

Adding `compinit conda` after `source $ZSH/oh-my-zsh.sh` in  `~/.zshrc` fixed it.

I also use the git plugin so the section of  `~/.zshrc` now looks like this:
```
plugins=(git conda-zsh-completion)

source $ZSH/oh-my-zsh.sh
 
compinit conda
```
 If this is the correct approach (someone more experienced with this should answer) I belive the documentation should be updated.

**Comment by esc** [comment] 2019-10-28 16:34
Does the following help: https://github.com/esc/conda-zsh-completion/pull/25

**Comment by haugstve** [comment] 2019-11-03 12:35
I installed after the branch was merged. 

Having some more time this weekend I tried the config from the docs once more. This time it worked.  My .zshrc now has these two lines
```
plugins=(git conda-zsh-completion)
autoload -U compinit && compinit
```

I tried to track down my original mistake to help others in a similar situation; I couldn't.  Whatever newbie mistake I made, it is hard to reproduce. 

**Thanks the the developers and maintainers for making my life easier.**

PS. I haven't tested is if the `compinit conda` command just needs to run once. I'm not even sure if that make sense.

**Comment by esc** [comment] 2019-11-04 13:27
@haugstve thanks for the feedback, we appreciate it!

**Comment by haugstve** [comment] 2019-12-01 14:11
The problem reappeared. It was probably never sorted, but only bypassed by me fiddling around and some how ended up running .zshrc multiple times in the same terminal or something. 

Who knows and who cares. This is what I used to solve it: #26 

I really appreciate the plugin!
